app = "fake-minecraft-motd"

[[services]]
  internal_port = 25565
  protocol = "tcp"

  [[services.ports]]
    port = 25565

  auto_start = true
  auto_stop = false

  [[services.checks]]
    type     = "tcp"
    interval = "10s"
    timeout  = "2s"
